name: predictatops
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _nb_ext_conf=0.4.0=py36_1
  - anaconda-client=1.6.14=py36_0
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.3=py36_0
  - bokeh=0.13.0=py36_0
  - cffi=1.11.5=py36h342bebf_0
  - chardet=3.0.4=py36h96c241c_1
  - click=6.7=py36hec950be_0
  - cloudpickle=0.5.3=py36_0
  - clyent=1.2.2=py36hae3ad88_0
  - cryptography=2.2.2=py36h1de35cc_0
  - cycler=0.10.0=py36hfc81398_0
  - cytoolz=0.9.0.1=py36h1de35cc_0
  - decorator=4.3.0=py36_0
  - distributed=1.22.0=py36_0
  - entrypoints=0.2.3=py36hd81d71f_2
  - freetype=2.9.1=hb4e5f40_0
  - heapdict=1.0.0=py36_2
  - html5lib=1.0.1=py36h2f9c1c0_0
  - idna=2.7=py36_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.2.1=py36_0
  - jedi=0.12.0=py36_1
  - jinja2=2.10.1=py36hd36f9c5_0
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_core=4.4.0=py36h79cf704_0
  - kiwisolver=1.0.1=py36h792292d_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.34=he12f830_0
  - libsodium=1.0.16=h3efe00b_0
  - locket=0.2.0=py36hca03003_1
  - markupsafe=1.0=py36h3a1e703_1
  - matplotlib=2.2.2=py36hbf02d85_2
  - mistune=0.8.3=py36h1de35cc_1
  - mkl_fft=1.0.4=py36h5d10147_1
  - mkl_random=1.0.1=py36h5d10147_1
  - msgpack-python=0.5.6=py36h04f5b5a_0
  - multipledispatch=0.5.0=py36_0
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.1=py36h349edbb_0
  - nb_conda_kernels=2.1.0=py36_0
  - nbconvert=5.3.1=py36h810822e_0
  - nbformat=4.4.0=py36h827af21_0
  - nbpresent=3.0.2=py36hef4c988_1
  - ncurses=6.1=h0a44026_0
  - notebook=5.5.0=py36_0
  - numpy=1.15.0=py36h648b28d_0
  - numpy-base=1.15.0=py36h8a80b8c_0
  - packaging=17.1=py36_0
  - pandoc=2.2.1=h1a437c5_0
  - pandocfilters=1.4.2=py36h3b0b094_1
  - parso=0.2.1=py36_0
  - partd=0.3.8=py36hf5c4cb8_0
  - patsy=0.5.0=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pip=10.0.1=py36_0
  - prompt_toolkit=1.0.15=py36haeda067_0
  - psutil=5.4.6=py36h1de35cc_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.18=py36h724b2fc_1
  - pygments=2.2.0=py36h240cd3f_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36hb281f35_0
  - pysocks=1.6.8=py36_0
  - python=3.6.6=hc167b69_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - pyyaml=3.12=py36h2ba1e63_1
  - pyzmq=17.0.0=py36h1de35cc_1
  - qtconsole=4.3.1=py36_0
  - readline=7.0=hc1231fa_4
  - requests=2.20.1=py36_0
  - scikit-learn=0.19.1=py36hf9f1f73_0
  - scipy=1.1.0=py36hf1f7d93_0
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - six=1.11.0=py36h0e22d5e_1
  - sortedcontainers=2.0.4=py36_0
  - sqlite=3.24.0=ha441bb4_0
  - statsmodels=0.9.0=py36h1d22016_0
  - tblib=1.3.2=py36hda67792_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h625a49b_0
  - tk=8.6.7=h35a86e2_3
  - toolz=0.9.0=py36_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - urllib3=1.24=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36h3b9701d_1
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.2.5=h378b8a2_0
  - zict=0.1.3=py36h71da714_0
  - zlib=1.2.11=hf3cbc9b_2
  - dask=0.18.2=py_0
  - dask-core=0.18.2=py_0
  - dask-glm=0.1.0=0
  - dask-ml=0.7.0=py36h470a237_0
  - hdbscan=0.8.15=py36h7eb728f_0
  - icu=58.2=hfc679d8_0
  - jpeg=9c=h470a237_0
  - jupyter=1.0.0=py_1
  - llvm-meta=6.0.0=0
  - llvmlite=0.23.0=py36_1
  - openmp=6.0.0=1
  - pandas=0.23.3=py36hf8a1672_1
  - pyqt=5.6.0=py36h8210e8a_6
  - qt=5.6.2=hd4c90f3_8
  - sip=4.18=py36_1
  - vega=1.3.0=py36_0
  - xgboost=0.72.1=py36hfc679d8_1
  - astroid=2.2.5=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - isort=4.3.15=py36_0
  - lazy-object-proxy=1.3.1=py36h1de35cc_2
  - mccabe=0.6.1=py36_1
  - mkl=2018.0.3=1
  - openssl=1.0.2o=h1de35cc_1
  - pylint=2.3.1=py36_0
  - typed-ast=1.3.1=py36h1de35cc_0
  - wrapt=1.11.1=py36h1de35cc_0
  - pip:
    - appdirs==1.4.3
    - branca==0.3.0
    - cython==0.28.3
    - dask-xgboost==0.1.5
    - folium==0.5.0
    - lasio==0.21
    - msgpack==0.5.6
    - numba==0.39.0
    - numexpr==2.6.5
    - ordereddict==1.1
    - pdvega==0.1
    - pooch==0.3.1
    - striplog==0.7.3
    - tables==3.4.4
    - tqdm==4.23.4
    - umap-learn==0.3.2
    - vega3==0.13.0
    - welly==0.3.5
prefix: /Users/justingosses/anaconda/envs/predictatops

